/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

// Source: schema.json
export type Notification = {
  _id: string;
  _type: "notification";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  recipient?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "user";
  };
  sender?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "user";
  };
  type?: "answer" | "follow" | "vote";
  question?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "question";
  };
  read?: boolean;
  createdAt?: string;
};

export type Vote = {
  _id: string;
  _type: "vote";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  user?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "user";
  };
  voteType?: "upvote" | "downvote";
  post?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "post";
  };
  comment?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "comment";
  };
  createdAt?: string;
};

export type Comment = {
  _id: string;
  _type: "comment";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  comment?: string;
  author?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "user";
  };
  post?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "post";
  };
  answer?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "answer";
  };
  parentComment?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "comment";
  };
  isReported?: boolean;
  isDeleted?: boolean;
  createdAt?: string;
};

export type Answer = {
  _id: string;
  _type: "answer";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  content?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  } | {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
    _key: string;
  }>;
  question?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "question";
  };
  author?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "user";
  };
  isAccepted?: boolean;
  isEdited?: boolean;
  editedAt?: string;
  createdAt?: string;
};

export type Question = {
  _id: string;
  _type: "question";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  description?: string;
  author?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "user";
  };
  category?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "category";
  };
  tags?: Array<string>;
  isAnswered?: boolean;
  isDeleted?: boolean;
  isClosed?: boolean;
  viewCount?: number;
  createdAt?: string;
  updatedAt?: string;
};

export type Post = {
  _id: string;
  _type: "post";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  postTitle?: string;
  originalTitle?: string;
  tags?: Array<string>;
  author?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "user";
  };
  category?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "category";
  };
  subreddit?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "subreddit";
  };
  body?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  image?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  contentGallery?: Array<{
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
    _key: string;
  } | {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.fileAsset";
    };
    media?: unknown;
    _type: "file";
    _key: string;
  }>;
  isReported?: boolean;
  publishedAt?: string;
  isDeleted?: boolean;
};

export type Category = {
  _id: string;
  _type: "category";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  description?: string;
  icon?: string;
  color?: "blue" | "green" | "red" | "purple" | "orange" | "pink" | "gray";
  isActive?: boolean;
  questionCount?: number;
  createdAt?: string;
};

export type Subreddit = {
  _id: string;
  _type: "subreddit";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  description?: string;
  slug?: Slug;
  image?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  moderator?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "user";
  };
  createdAt?: string;
};

export type User = {
  _id: string;
  _type: "user";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  username?: string;
  email?: string;
  imageUrl?: string;
  clerkId?: string;
  bio?: string;
  joinedAt?: string;
  isReported?: boolean;
  bookmarks?: Array<{
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    _key: string;
    [internalGroqTypeReferenceTo]?: "question";
  }>;
  followers?: Array<{
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    _key: string;
    [internalGroqTypeReferenceTo]?: "user";
  }>;
  following?: Array<{
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    _key: string;
    [internalGroqTypeReferenceTo]?: "user";
  }>;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type AllSanitySchemaTypes = Notification | Vote | Comment | Answer | Question | Post | Category | Subreddit | User | SanityImagePaletteSwatch | SanityImagePalette | SanityImageDimensions | SanityImageHotspot | SanityImageCrop | SanityFileAsset | SanityImageAsset | SanityImageMetadata | Geopoint | Slug | SanityAssetSourceData;
export declare const internalGroqTypeReferenceTo: unique symbol;
// Source: ./src/app/(app)/communities/page.tsx
// Variable: communitiesQuery
// Query: *[_type == "subreddit" && !isDeleted] | order(createdAt desc) {    _id,    title,    description,    slug,    "memberCount": count(*[_type == "user" && references(^._id)]),    "postCount": count(*[_type == "post" && references(^._id) && !isDeleted]),    createdAt  }
export type CommunitiesQueryResult = Array<never>;

// Source: ./src/app/(app)/community/[slug]/create-post/page.tsx
// Variable: subredditQuery
// Query: *[_type == "subreddit" && slug.current == $slug][0]{    _id,    title,    slug,  }
export type SubredditQueryResult = {
  _id: string;
  title: string | null;
  slug: Slug | null;
} | null;

// Source: ./src/app/(app)/community/[slug]/page.tsx
// Variable: communityQuery
// Query: *[_type == "subreddit" && slug.current == $slug][0] {        _id,        title,        description,        image,        moderator->{          username        },        createdAt      }
export type CommunityQueryResult = {
  _id: string;
  title: string | null;
  description: string | null;
  image: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  } | null;
  moderator: {
    username: string | null;
  } | null;
  createdAt: string | null;
} | null;
// Variable: postsQuery
// Query: *[_type == "post" && !isDeleted && subreddit->slug.current == $slug] | order(publishedAt desc) [0...20] {        _id,        postTitle,        body,        image,        publishedAt,        author->{          username,          imageUrl        },        subreddit->{          title,          slug        }      }
export type PostsQueryResult = Array<{
  _id: string;
  postTitle: string | null;
  body: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }> | null;
  image: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  } | null;
  publishedAt: string | null;
  author: {
    username: string | null;
    imageUrl: string | null;
  } | null;
  subreddit: {
    title: string | null;
    slug: Slug | null;
  } | null;
}>;

// Source: ./src/app/(app)/create-post/page.tsx
// Variable: categoriesQuery
// Query: *[_type == "category"] | order(name asc) {    _id,    name,    slug,    description,    icon,    color,    "questionCount": count(*[_type == "question" && references(^._id)])  }
export type CategoriesQueryResult = Array<{
  _id: string;
  name: string | null;
  slug: Slug | null;
  description: string | null;
  icon: string | null;
  color: "blue" | "gray" | "green" | "orange" | "pink" | "purple" | "red" | null;
  questionCount: number;
}>;

// Source: ./src/app/(app)/post/[id]/page.tsx
// Variable: postQuery
// Query: *[_type == "post" && _id == $id && !isDeleted][0] {        _id,        postTitle,        body,        image,        contentGallery[]{          _type,          asset->{            url          },          alt,          title        },        publishedAt,        author->{          username,          imageUrl,          clerkId        },        subreddit->{          title,          slug        },        category->{          name,          slug,          icon        }      }
export type PostQueryResult = {
  _id: string;
  postTitle: string | null;
  body: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }> | null;
  image: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  } | null;
  contentGallery: Array<{
    _type: "file";
    asset: {
      url: string | null;
    } | null;
    alt: null;
    title: null;
  } | {
    _type: "image";
    asset: {
      url: string | null;
    } | null;
    alt: null;
    title: null;
  }> | null;
  publishedAt: string | null;
  author: {
    username: string | null;
    imageUrl: string | null;
    clerkId: string | null;
  } | null;
  subreddit: {
    title: string | null;
    slug: Slug | null;
  } | null;
  category: {
    name: string | null;
    slug: Slug | null;
    icon: string | null;
  } | null;
} | null;
// Variable: commentsQuery
// Query: *[_type == "comment" && post._ref == $id && !isDeleted] | order(createdAt asc) {        _id,        comment,        createdAt,        author->{          username,          imageUrl,          clerkId        },        parentComment      }
export type CommentsQueryResult = Array<{
  _id: string;
  comment: string | null;
  createdAt: string | null;
  author: {
    username: string | null;
    imageUrl: string | null;
    clerkId: string | null;
  } | null;
  parentComment: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "comment";
  } | null;
}>;

// Source: ./src/app/(app)/profile/[username]/page.tsx
// Variable: userQuery
// Query: *[_type == "user" && username == $username][0] {    _id,    clerkId,    username,    imageUrl,    bio,    joinedAt,    "questionsCount": count(*[_type == "question" && author._ref == ^._id && !isDeleted]),    "answersCount": count(*[_type == "answer" && author._ref == ^._id && !isDeleted]),    "postsCount": count(*[_type == "post" && author._ref == ^._id && !isDeleted]),    "followersCount": count(coalesce(followers, [])),    "followingCount": count(coalesce(following, [])),    "followers": coalesce(followers, [])[]->{ _id, username, imageUrl },    "following": coalesce(following, [])[]->{ _id, username, imageUrl }  }
export type UserQueryResult = {
  _id: string;
  clerkId: string | null;
  username: string | null;
  imageUrl: string | null;
  bio: string | null;
  joinedAt: string | null;
  questionsCount: number;
  answersCount: number;
  postsCount: number;
  followersCount: number;
  followingCount: number;
  followers: Array<{
    _id: string;
    username: string | null;
    imageUrl: string | null;
  }> | Array<never>;
  following: Array<{
    _id: string;
    username: string | null;
    imageUrl: string | null;
  }> | Array<never>;
} | null;
// Variable: userQuestionsQuery
// Query: *[_type == "question" && author._ref == $userId && !isDeleted] | order(createdAt desc) [0...10] {    _id,    title,    createdAt,    "answerCount": count(*[_type == "answer" && references(^._id) && !isDeleted]),    category->{      name,      color    }  }
export type UserQuestionsQueryResult = Array<{
  _id: string;
  title: string | null;
  createdAt: string | null;
  answerCount: number;
  category: {
    name: string | null;
    color: "blue" | "gray" | "green" | "orange" | "pink" | "purple" | "red" | null;
  } | null;
}>;
// Variable: userAnswersQuery
// Query: *[_type == "answer" && author._ref == $userId && !isDeleted] | order(createdAt desc) [0...10] {    _id,    content,    question->{      _id,      title    },    createdAt,    "voteCount": coalesce(count(votes[].voteType == "upvote") - count(votes[].voteType == "downvote"), 0)  }
export type UserAnswersQueryResult = Array<never>;
// Variable: userPostsQuery
// Query: *[_type == "post" && author._ref == $userId && !isDeleted] | order(publishedAt desc) [0...10] {    _id,    postTitle,    body,    image,    publishedAt,    subreddit->{      title,      slug    },    "commentCount": count(*[_type == "comment" && references(^._id) && !isDeleted])  }
export type UserPostsQueryResult = Array<{
  _id: string;
  postTitle: string | null;
  body: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }> | null;
  image: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  } | null;
  publishedAt: string | null;
  subreddit: {
    title: string | null;
    slug: Slug | null;
  } | null;
  commentCount: number;
}>;
// Variable: caseInsensitiveQuery
// Query: *[_type == "user" && lower(username) == lower($username)][0] {          _id,          clerkId,          username,          imageUrl,          bio,          joinedAt,          "questionsCount": count(*[_type == "question" && author._ref == ^._id && !isDeleted]),          "answersCount": count(*[_type == "answer" && author._ref == ^._id && !isDeleted]),          "postsCount": count(*[_type == "post" && author._ref == ^._id && !isDeleted]),          "followersCount": count(coalesce(followers, [])),          "followingCount": count(coalesce(following, [])),          "followers": coalesce(followers, [])[]->{ _id, username, imageUrl },          "following": coalesce(following, [])[]->{ _id, username, imageUrl }        }
export type CaseInsensitiveQueryResult = {
  _id: string;
  clerkId: string | null;
  username: string | null;
  imageUrl: string | null;
  bio: string | null;
  joinedAt: string | null;
  questionsCount: number;
  answersCount: number;
  postsCount: number;
  followersCount: number;
  followingCount: number;
  followers: Array<{
    _id: string;
    username: string | null;
    imageUrl: string | null;
  }> | Array<never>;
  following: Array<{
    _id: string;
    username: string | null;
    imageUrl: string | null;
  }> | Array<never>;
} | null;

// Source: ./src/app/(app)/question/[id]/page.tsx
// Variable: questionQuery
// Query: *[_type == "question" && _id == $id && !isDeleted][0] {    _id,    title,    description,    author->{      _id,      username,      imageUrl,      bio,      clerkId    },    category->{      name,      color,      slug    },    tags,    createdAt,    updatedAt,    "answerCount": count(*[_type == "answer" && references(^._id) && !isDeleted]),    "viewCount": 0,    "followerCount": 0,    "isFollowing": false,    "isBookmarked": false,    "answers": *[_type == "answer" && references(^._id) && !isDeleted] | order(createdAt desc) {      _id,      content,      author->{        _id,        username,        imageUrl,        bio,        clerkId      },      createdAt,      updatedAt,      "voteCount": coalesce(count(votes[].voteType == "upvote") - count(votes[].voteType == "downvote"), 0),      "userVote": null,      "isAccepted": false,      "commentCount": 0,      "comments": []    }  }
export type QuestionQueryResult = {
  _id: string;
  title: string | null;
  description: string | null;
  author: {
    _id: string;
    username: string | null;
    imageUrl: string | null;
    bio: string | null;
    clerkId: string | null;
  } | null;
  category: {
    name: string | null;
    color: "blue" | "gray" | "green" | "orange" | "pink" | "purple" | "red" | null;
    slug: Slug | null;
  } | null;
  tags: Array<string> | null;
  createdAt: string | null;
  updatedAt: string | null;
  answerCount: number;
  viewCount: 0;
  followerCount: 0;
  isFollowing: false;
  isBookmarked: false;
  answers: Array<never>;
} | null;

// Source: ./src/app/api/categories/route.ts
// Variable: getCategoriesQuery
// Query: *[_type == "category"] | order(createdAt desc) {    _id,    name,    "slug": slug.current,    description,    icon,    color,    "questionCount": count(*[_type == "question" && references(^._id) && !isDeleted])  }
export type GetCategoriesQueryResult = Array<{
  _id: string;
  name: string | null;
  slug: string | null;
  description: string | null;
  icon: string | null;
  color: "blue" | "gray" | "green" | "orange" | "pink" | "purple" | "red" | null;
  questionCount: number;
}>;

// Source: ./src/app/api/get-current-user/route.ts
// Variable: currentUserQuery
// Query: *[_type == "user" && clerkId == $userId][0] {        _id,        username,        email,        imageUrl,        clerkId      }
export type CurrentUserQueryResult = {
  _id: string;
  username: string | null;
  email: string | null;
  imageUrl: string | null;
  clerkId: string | null;
} | null;

// Source: ./src/app/api/notifications/mark-all-read/route.ts
// Variable: userQueryNotifyRead
// Query: *[_type == "user" && (clerkId == $userId || _id == $userId)][0]._id
export type UserQueryNotifyReadResult = string | null;
// Variable: query
// Query: *[_type == "notification" && recipient._ref == $sanityUserId && !read]._id
export type QueryResult = Array<string>;

// Source: ./src/app/api/notifications/route.ts
// Variable: userQueryNotifyList
// Query: *[_type == "user" && (clerkId == $userId || _id == $userId)][0]._id
export type UserQueryNotifyListResult = string | null;
// Variable: notificationsListQuery
// Query: *[_type == "notification" && recipient._ref == $sanityUserId] | order(createdAt desc) {            _id,            type,            read,            createdAt,            sender->{                username,                imageUrl            },            question->{                _id,                title,                slug            }        }
export type NotificationsListQueryResult = Array<{
  _id: string;
  type: "answer" | "follow" | "vote" | null;
  read: boolean | null;
  createdAt: string | null;
  sender: {
    username: string | null;
    imageUrl: string | null;
  } | null;
  question: {
    _id: string;
    title: string | null;
    slug: null;
  } | null;
}>;

// Source: ./src/app/api/notifications/unread-count/route.ts
// Variable: userQueryNotifyCount
// Query: *[_type == "user" && (clerkId == $userId || _id == $userId)][0]._id
export type UserQueryNotifyCountResult = string | null;
// Variable: unreadNotificationsCountQuery
// Query: count(*[_type == "notification" && recipient._ref == $sanityUserId && !read])
export type UnreadNotificationsCountQueryResult = number;

// Source: ./src/app/api/search/route.ts
// Variable: searchQuestionsQuery
// Query: *[_type == "question" && !isDeleted && (        title match $searchTerm ||        description match $searchTerm ||        tags[] match $searchTerm      )] | order(createdAt desc) [0...10] {        _id,        title,        description,        author->{          username,          imageUrl        },        category->{          name,          color        },        tags,        createdAt,        "answerCount": count(*[_type == "answer" && references(^._id) && !isDeleted])      }
export type SearchQuestionsQueryResult = Array<{
  _id: string;
  title: string | null;
  description: string | null;
  author: {
    username: string | null;
    imageUrl: string | null;
  } | null;
  category: {
    name: string | null;
    color: "blue" | "gray" | "green" | "orange" | "pink" | "purple" | "red" | null;
  } | null;
  tags: Array<string> | null;
  createdAt: string | null;
  answerCount: number;
}>;
// Variable: searchPostsQuery
// Query: *[_type == "post" && !isDeleted && (        postTitle match $searchTerm ||        body[].children[].text match $searchTerm      )] | order(publishedAt desc) [0...10] {        _id,        postTitle,        body,        image,        author->{          username,          imageUrl        },        subreddit->{          title,          slug        },        publishedAt,        "commentCount": count(*[_type == "comment" && references(^._id) && !isDeleted])      }
export type SearchPostsQueryResult = Array<{
  _id: string;
  postTitle: string | null;
  body: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }> | null;
  image: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  } | null;
  author: {
    username: string | null;
    imageUrl: string | null;
  } | null;
  subreddit: {
    title: string | null;
    slug: Slug | null;
  } | null;
  publishedAt: string | null;
  commentCount: number;
}>;
// Variable: usersQuery
// Query: *[_type == "user" && (        username match $searchTerm ||        email match $searchTerm      )] | order(joinedAt desc) [0...10] {        _id,        username,        email,        imageUrl,        bio,        joinedAt      }
export type UsersQueryResult = Array<{
  _id: string;
  username: string | null;
  email: string | null;
  imageUrl: string | null;
  bio: string | null;
  joinedAt: string | null;
}>;
// Variable: answersQuery
// Query: *[_type == "answer" && !isDeleted && (        content[].children[].text match $searchTerm      )] | order(createdAt desc) [0...10] {        _id,        content,        author->{          username,          imageUrl        },        question->{          _id,          title        },        createdAt,        "voteCount": coalesce(          count(*[_type == "vote" && references(^._id) && voteType == "upvote"]) -          count(*[_type == "vote" && references(^._id) && voteType == "downvote"]),          0        )      }
export type AnswersQueryResult = Array<never>;

// Source: ./src/app/api/sync-user/route.ts
// Variable: existingUserQuery
// Query: *[_type == "user" && _id == $userId][0] {        _id,        username,        email,        imageUrl      }
export type ExistingUserQueryResult = {
  _id: string;
  username: string | null;
  email: string | null;
  imageUrl: string | null;
} | null;
// Variable: syncUserQuery
// Query: *[_type == "user" && _id == $userId][0] {        _id,        username,        email,        imageUrl,        joinedAt      }
export type SyncUserQueryResult = {
  _id: string;
  username: string | null;
  email: string | null;
  imageUrl: string | null;
  joinedAt: string | null;
} | null;

// Source: ./src/app/api/votes/route.ts
// Variable: postVoteQuery
// Query: *[_type == "vote" && user._ref == $userId && post._ref == $targetId][0] {        _id,        voteType      }
export type PostVoteQueryResult = {
  _id: string;
  voteType: "downvote" | "upvote" | null;
} | null;
// Variable: commentVoteQuery
// Query: *[_type == "vote" && user._ref == $userId && comment._ref == $targetId][0] {        _id,        voteType      }
export type CommentVoteQueryResult = {
  _id: string;
  voteType: "downvote" | "upvote" | null;
} | null;
// Variable: postVoteStatsQuery
// Query: {        "votes": *[_type == "vote" && post._ref == $targetId] {          voteType        },        "userVote": *[_type == "vote" && user._ref == $userId && post._ref == $targetId][0] {          voteType        }      }
export type PostVoteStatsQueryResult = {
  votes: Array<{
    voteType: "downvote" | "upvote" | null;
  }>;
  userVote: {
    voteType: "downvote" | "upvote" | null;
  } | null;
};
// Variable: commentVoteStatsQuery
// Query: {        "votes": *[_type == "vote" && comment._ref == $targetId] {          voteType        },        "userVote": *[_type == "vote" && user._ref == $userId && comment._ref == $targetId][0] {          voteType        }      }
export type CommentVoteStatsQueryResult = {
  votes: Array<{
    voteType: "downvote" | "upvote" | null;
  }>;
  userVote: {
    voteType: "downvote" | "upvote" | null;
  } | null;
};

// Source: ./src/app/page.tsx
// Variable: homeQuestionsQuery
// Query: *[_type == "question" && !isDeleted] | order(createdAt desc) [0...20] {    _id,    title,    description,    author->{      username,      imageUrl,      clerkId    },    category->{      _id,      name,      color,      icon    },    image{      asset->{        url      },      alt    },    tags,    isAnswered,    isDeleted,    createdAt,    "answerCount": count(*[_type == "answer" && references(^._id) && !isDeleted]),    "voteCount": 0,    "topAnswer": *[_type == "answer" && references(^._id) && !isDeleted] | order(createdAt asc) [0] {      _id,      content,      author->{        username,        imageUrl,        clerkId      },      createdAt    }  }
export type HomeQuestionsQueryResult = Array<{
  _id: string;
  title: string | null;
  description: string | null;
  author: {
    username: string | null;
    imageUrl: string | null;
    clerkId: string | null;
  } | null;
  category: {
    _id: string;
    name: string | null;
    color: "blue" | "gray" | "green" | "orange" | "pink" | "purple" | "red" | null;
    icon: string | null;
  } | null;
  image: null;
  tags: Array<string> | null;
  isAnswered: boolean | null;
  isDeleted: boolean | null;
  createdAt: string | null;
  answerCount: number;
  voteCount: 0;
  topAnswer: null;
}>;
// Variable: homePostsQuery
// Query: *[_type == "post" && !isDeleted] | order(publishedAt desc) [0...10] {    _id,    postTitle,    body,    image{      "_type": "image",      asset->{        url,        metadata      },      alt    },    contentGallery[]{      _type,      asset->{        url      },      alt,      title    },    author->{      username,      imageUrl,      clerkId    },    subreddit->{      title,      slug    },    category->{      name,      slug    },    publishedAt,    tags,    "commentCount": count(*[_type == "comment" && references(^._id) && !isDeleted])  }
export type HomePostsQueryResult = Array<{
  _id: string;
  postTitle: string | null;
  body: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }> | null;
  image: {
    _type: "image";
    asset: {
      url: string | null;
      metadata: SanityImageMetadata | null;
    } | null;
    alt: string | null;
  } | null;
  contentGallery: Array<{
    _type: "file";
    asset: {
      url: string | null;
    } | null;
    alt: null;
    title: null;
  } | {
    _type: "image";
    asset: {
      url: string | null;
    } | null;
    alt: null;
    title: null;
  }> | null;
  author: {
    username: string | null;
    imageUrl: string | null;
    clerkId: string | null;
  } | null;
  subreddit: {
    title: string | null;
    slug: Slug | null;
  } | null;
  category: {
    name: string | null;
    slug: Slug | null;
  } | null;
  publishedAt: string | null;
  tags: Array<string> | null;
  commentCount: number;
}>;
// Variable: categoriesQueryHome
// Query: *[_type == "category"] | order(name asc) {    _id,    name,    "slug": slug.current,    color  }
export type CategoriesQueryHomeResult = Array<{
  _id: string;
  name: string | null;
  slug: string | null;
  color: "blue" | "gray" | "green" | "orange" | "pink" | "purple" | "red" | null;
}>;
// Variable: homeCommunitiesQuery
// Query: *[_type == "subreddit"] | order(createdAt desc) [0...5] {    _id,    title,    slug,    description,    image{      asset->{        url      }    }  }
export type HomeCommunitiesQueryResult = Array<{
  _id: string;
  title: string | null;
  slug: Slug | null;
  description: string | null;
  image: {
    asset: {
      url: string | null;
    } | null;
  } | null;
}>;

// Source: ./src/sanity/lib/subreddit/createSubreddit.ts
// Variable: checkExistingQuery
// Query: *[_type=="subreddit" && title == $name][0]{            _id}
export type CheckExistingQueryResult = {
  _id: string;
} | null;
// Variable: checkSlugQuery
// Query: *[_type == "subreddit" && slug.current == $slug][0]{            _id            }
export type CheckSlugQueryResult = {
  _id: string;
} | null;

// Source: ./src/sanity/lib/subreddit/getSubreddit.ts
// Variable: getSubredditsQuery
// Query: *[_type == "subreddit"] {        ...,          "slug": slug.current,                   "moderator":moderator->,                    } |order(createdAt desc)
export type GetSubredditsQueryResult = Array<{
  _id: string;
  _type: "subreddit";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  description?: string;
  slug: string | null;
  image?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  moderator: {
    _id: string;
    _type: "user";
    _createdAt: string;
    _updatedAt: string;
    _rev: string;
    username?: string;
    email?: string;
    imageUrl?: string;
    clerkId?: string;
    bio?: string;
    joinedAt?: string;
    isReported?: boolean;
    bookmarks?: Array<{
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      _key: string;
      [internalGroqTypeReferenceTo]?: "question";
    }>;
    followers?: Array<{
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      _key: string;
      [internalGroqTypeReferenceTo]?: "user";
    }>;
    following?: Array<{
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      _key: string;
      [internalGroqTypeReferenceTo]?: "user";
    }>;
  } | null;
  createdAt?: string;
}>;

// Source: ./src/sanity/lib/user/getUser.ts
// Variable: getExistingUserQuery
// Query: *[_type == "user" && (_id == $id || clerkId == $id)][0]
export type GetExistingUserQueryResult = {
  _id: string;
  _type: "user";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  username?: string;
  email?: string;
  imageUrl?: string;
  clerkId?: string;
  bio?: string;
  joinedAt?: string;
  isReported?: boolean;
  bookmarks?: Array<{
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    _key: string;
    [internalGroqTypeReferenceTo]?: "question";
  }>;
  followers?: Array<{
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    _key: string;
    [internalGroqTypeReferenceTo]?: "user";
  }>;
  following?: Array<{
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    _key: string;
    [internalGroqTypeReferenceTo]?: "user";
  }>;
} | null;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    "\n  *[_type == \"subreddit\" && !isDeleted] | order(createdAt desc) {\n    _id,\n    title,\n    description,\n    slug,\n    \"memberCount\": count(*[_type == \"user\" && references(^._id)]),\n    \"postCount\": count(*[_type == \"post\" && references(^._id) && !isDeleted]),\n    createdAt\n  }\n": CommunitiesQueryResult;
    "\n  *[_type == \"subreddit\" && slug.current == $slug][0]{\n    _id,\n    title,\n    slug,\n  }\n": SubredditQueryResult;
    "\n      *[_type == \"subreddit\" && slug.current == $slug][0] {\n        _id,\n        title,\n        description,\n        image,\n        moderator->{\n          username\n        },\n        createdAt\n      }\n    ": CommunityQueryResult;
    "\n      *[_type == \"post\" && !isDeleted && subreddit->slug.current == $slug] | order(publishedAt desc) [0...20] {\n        _id,\n        postTitle,\n        body,\n        image,\n        publishedAt,\n        author->{\n          username,\n          imageUrl\n        },\n        subreddit->{\n          title,\n          slug\n        }\n      }\n    ": PostsQueryResult;
    "\n  *[_type == \"category\"] | order(name asc) {\n    _id,\n    name,\n    slug,\n    description,\n    icon,\n    color,\n    \"questionCount\": count(*[_type == \"question\" && references(^._id)])\n  }\n": CategoriesQueryResult;
    "\n      *[_type == \"post\" && _id == $id && !isDeleted][0] {\n        _id,\n        postTitle,\n        body,\n        image,\n        contentGallery[]{\n          _type,\n          asset->{\n            url\n          },\n          alt,\n          title\n        },\n        publishedAt,\n        author->{\n          username,\n          imageUrl,\n          clerkId\n        },\n        subreddit->{\n          title,\n          slug\n        },\n        category->{\n          name,\n          slug,\n          icon\n        }\n      }\n    ": PostQueryResult;
    "\n      *[_type == \"comment\" && post._ref == $id && !isDeleted] | order(createdAt asc) {\n        _id,\n        comment,\n        createdAt,\n        author->{\n          username,\n          imageUrl,\n          clerkId\n        },\n        parentComment\n      }\n    ": CommentsQueryResult;
    "\n  *[_type == \"user\" && username == $username][0] {\n    _id,\n    clerkId,\n    username,\n    imageUrl,\n    bio,\n    joinedAt,\n    \"questionsCount\": count(*[_type == \"question\" && author._ref == ^._id && !isDeleted]),\n    \"answersCount\": count(*[_type == \"answer\" && author._ref == ^._id && !isDeleted]),\n    \"postsCount\": count(*[_type == \"post\" && author._ref == ^._id && !isDeleted]),\n    \"followersCount\": count(coalesce(followers, [])),\n    \"followingCount\": count(coalesce(following, [])),\n    \"followers\": coalesce(followers, [])[]->{ _id, username, imageUrl },\n    \"following\": coalesce(following, [])[]->{ _id, username, imageUrl }\n  }\n": UserQueryResult;
    "\n  *[_type == \"question\" && author._ref == $userId && !isDeleted] | order(createdAt desc) [0...10] {\n    _id,\n    title,\n    createdAt,\n    \"answerCount\": count(*[_type == \"answer\" && references(^._id) && !isDeleted]),\n    category->{\n      name,\n      color\n    }\n  }\n": UserQuestionsQueryResult;
    "\n  *[_type == \"answer\" && author._ref == $userId && !isDeleted] | order(createdAt desc) [0...10] {\n    _id,\n    content,\n    question->{\n      _id,\n      title\n    },\n    createdAt,\n    \"voteCount\": coalesce(count(votes[].voteType == \"upvote\") - count(votes[].voteType == \"downvote\"), 0)\n  }\n": UserAnswersQueryResult;
    "\n  *[_type == \"post\" && author._ref == $userId && !isDeleted] | order(publishedAt desc) [0...10] {\n    _id,\n    postTitle,\n    body,\n    image,\n    publishedAt,\n    subreddit->{\n      title,\n      slug\n    },\n    \"commentCount\": count(*[_type == \"comment\" && references(^._id) && !isDeleted])\n  }\n": UserPostsQueryResult;
    "\n        *[_type == \"user\" && lower(username) == lower($username)][0] {\n          _id,\n          clerkId,\n          username,\n          imageUrl,\n          bio,\n          joinedAt,\n          \"questionsCount\": count(*[_type == \"question\" && author._ref == ^._id && !isDeleted]),\n          \"answersCount\": count(*[_type == \"answer\" && author._ref == ^._id && !isDeleted]),\n          \"postsCount\": count(*[_type == \"post\" && author._ref == ^._id && !isDeleted]),\n          \"followersCount\": count(coalesce(followers, [])),\n          \"followingCount\": count(coalesce(following, [])),\n          \"followers\": coalesce(followers, [])[]->{ _id, username, imageUrl },\n          \"following\": coalesce(following, [])[]->{ _id, username, imageUrl }\n        }\n      ": CaseInsensitiveQueryResult;
    "\n  *[_type == \"question\" && _id == $id && !isDeleted][0] {\n    _id,\n    title,\n    description,\n    author->{\n      _id,\n      username,\n      imageUrl,\n      bio,\n      clerkId\n    },\n    category->{\n      name,\n      color,\n      slug\n    },\n    tags,\n    createdAt,\n    updatedAt,\n    \"answerCount\": count(*[_type == \"answer\" && references(^._id) && !isDeleted]),\n    \"viewCount\": 0,\n    \"followerCount\": 0,\n    \"isFollowing\": false,\n    \"isBookmarked\": false,\n    \"answers\": *[_type == \"answer\" && references(^._id) && !isDeleted] | order(createdAt desc) {\n      _id,\n      content,\n      author->{\n        _id,\n        username,\n        imageUrl,\n        bio,\n        clerkId\n      },\n      createdAt,\n      updatedAt,\n      \"voteCount\": coalesce(count(votes[].voteType == \"upvote\") - count(votes[].voteType == \"downvote\"), 0),\n      \"userVote\": null,\n      \"isAccepted\": false,\n      \"commentCount\": 0,\n      \"comments\": []\n    }\n  }\n": QuestionQueryResult;
    "\n  *[_type == \"category\"] | order(createdAt desc) {\n    _id,\n    name,\n    \"slug\": slug.current,\n    description,\n    icon,\n    color,\n    \"questionCount\": count(*[_type == \"question\" && references(^._id) && !isDeleted])\n  }\n": GetCategoriesQueryResult;
    "\n      *[_type == \"user\" && clerkId == $userId][0] {\n        _id,\n        username,\n        email,\n        imageUrl,\n        clerkId\n      }\n    ": CurrentUserQueryResult;
    "*[_type == \"user\" && (clerkId == $userId || _id == $userId)][0]._id": UserQueryNotifyReadResult | UserQueryNotifyListResult | UserQueryNotifyCountResult;
    "*[_type == \"notification\" && recipient._ref == $sanityUserId && !read]._id": QueryResult;
    "*[_type == \"notification\" && recipient._ref == $sanityUserId] | order(createdAt desc) {\n            _id,\n            type,\n            read,\n            createdAt,\n            sender->{\n                username,\n                imageUrl\n            },\n            question->{\n                _id,\n                title,\n                slug\n            }\n        }": NotificationsListQueryResult;
    "count(*[_type == \"notification\" && recipient._ref == $sanityUserId && !read])": UnreadNotificationsCountQueryResult;
    "\n      *[_type == \"question\" && !isDeleted && (\n        title match $searchTerm ||\n        description match $searchTerm ||\n        tags[] match $searchTerm\n      )] | order(createdAt desc) [0...10] {\n        _id,\n        title,\n        description,\n        author->{\n          username,\n          imageUrl\n        },\n        category->{\n          name,\n          color\n        },\n        tags,\n        createdAt,\n        \"answerCount\": count(*[_type == \"answer\" && references(^._id) && !isDeleted])\n      }\n    ": SearchQuestionsQueryResult;
    "\n      *[_type == \"post\" && !isDeleted && (\n        postTitle match $searchTerm ||\n        body[].children[].text match $searchTerm\n      )] | order(publishedAt desc) [0...10] {\n        _id,\n        postTitle,\n        body,\n        image,\n        author->{\n          username,\n          imageUrl\n        },\n        subreddit->{\n          title,\n          slug\n        },\n        publishedAt,\n        \"commentCount\": count(*[_type == \"comment\" && references(^._id) && !isDeleted])\n      }\n    ": SearchPostsQueryResult;
    "\n      *[_type == \"user\" && (\n        username match $searchTerm ||\n        email match $searchTerm\n      )] | order(joinedAt desc) [0...10] {\n        _id,\n        username,\n        email,\n        imageUrl,\n        bio,\n        joinedAt\n      }\n    ": UsersQueryResult;
    "\n      *[_type == \"answer\" && !isDeleted && (\n        content[].children[].text match $searchTerm\n      )] | order(createdAt desc) [0...10] {\n        _id,\n        content,\n        author->{\n          username,\n          imageUrl\n        },\n        question->{\n          _id,\n          title\n        },\n        createdAt,\n        \"voteCount\": coalesce(\n          count(*[_type == \"vote\" && references(^._id) && voteType == \"upvote\"]) -\n          count(*[_type == \"vote\" && references(^._id) && voteType == \"downvote\"]),\n          0\n        )\n      }\n    ": AnswersQueryResult;
    "\n      *[_type == \"user\" && _id == $userId][0] {\n        _id,\n        username,\n        email,\n        imageUrl\n      }\n    ": ExistingUserQueryResult;
    "\n      *[_type == \"user\" && _id == $userId][0] {\n        _id,\n        username,\n        email,\n        imageUrl,\n        joinedAt\n      }\n    ": SyncUserQueryResult;
    "\n      *[_type == \"vote\" && user._ref == $userId && post._ref == $targetId][0] {\n        _id,\n        voteType\n      }\n    ": PostVoteQueryResult;
    "\n      *[_type == \"vote\" && user._ref == $userId && comment._ref == $targetId][0] {\n        _id,\n        voteType\n      }\n    ": CommentVoteQueryResult;
    "\n      {\n        \"votes\": *[_type == \"vote\" && post._ref == $targetId] {\n          voteType\n        },\n        \"userVote\": *[_type == \"vote\" && user._ref == $userId && post._ref == $targetId][0] {\n          voteType\n        }\n      }\n    ": PostVoteStatsQueryResult;
    "\n      {\n        \"votes\": *[_type == \"vote\" && comment._ref == $targetId] {\n          voteType\n        },\n        \"userVote\": *[_type == \"vote\" && user._ref == $userId && comment._ref == $targetId][0] {\n          voteType\n        }\n      }\n    ": CommentVoteStatsQueryResult;
    "\n  *[_type == \"question\" && !isDeleted] | order(createdAt desc) [0...20] {\n    _id,\n    title,\n    description,\n    author->{\n      username,\n      imageUrl,\n      clerkId\n    },\n    category->{\n      _id,\n      name,\n      color,\n      icon\n    },\n    image{\n      asset->{\n        url\n      },\n      alt\n    },\n    tags,\n    isAnswered,\n    isDeleted,\n    createdAt,\n    \"answerCount\": count(*[_type == \"answer\" && references(^._id) && !isDeleted]),\n    \"voteCount\": 0,\n    \"topAnswer\": *[_type == \"answer\" && references(^._id) && !isDeleted] | order(createdAt asc) [0] {\n      _id,\n      content,\n      author->{\n        username,\n        imageUrl,\n        clerkId\n      },\n      createdAt\n    }\n  }\n": HomeQuestionsQueryResult;
    "\n  *[_type == \"post\" && !isDeleted] | order(publishedAt desc) [0...10] {\n    _id,\n    postTitle,\n    body,\n    image{\n      \"_type\": \"image\",\n      asset->{\n        url,\n        metadata\n      },\n      alt\n    },\n    contentGallery[]{\n      _type,\n      asset->{\n        url\n      },\n      alt,\n      title\n    },\n    author->{\n      username,\n      imageUrl,\n      clerkId\n    },\n    subreddit->{\n      title,\n      slug\n    },\n    category->{\n      name,\n      slug\n    },\n    publishedAt,\n    tags,\n    \"commentCount\": count(*[_type == \"comment\" && references(^._id) && !isDeleted])\n  }\n": HomePostsQueryResult;
    "\n  *[_type == \"category\"] | order(name asc) {\n    _id,\n    name,\n    \"slug\": slug.current,\n    color\n  }\n": CategoriesQueryHomeResult;
    "\n  *[_type == \"subreddit\"] | order(createdAt desc) [0...5] {\n    _id,\n    title,\n    slug,\n    description,\n    image{\n      asset->{\n        url\n      }\n    }\n  }\n": HomeCommunitiesQueryResult;
    "\n*[_type==\"subreddit\" && title == $name][0]{\n            _id\n\n}": CheckExistingQueryResult;
    "\n            *[_type == \"subreddit\" && slug.current == $slug][0]{\n            _id\n            }\n            \n            ": CheckSlugQueryResult;
    "\n        *[_type == \"subreddit\"] {\n        ...,\n          \"slug\": slug.current,\n         \n          \"moderator\":moderator->,\n            \n        } |order(createdAt desc)\n    ": GetSubredditsQueryResult;
    "*[_type == \"user\" && (_id == $id || clerkId == $id)][0]": GetExistingUserQueryResult;
  }
}
